name: Augeas CI

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        shard_file:
          - shard.yml
        crystal_version:
          - 1.1.1
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install Augeas Package
        run: sudo apt-get install libaugeas-dev
      - name: Download source
        uses: actions/checkout@v2
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec
      - name: Check formatting
        run: crystal tool format --check src spec
